export const MAKE_API_CALL = "MAKE_API_CALL";

export const SEARCH_TXS = "SEARCH_TXS";
export const SEARCH_TXS_RESULTS_GOTO_PAGE = "SEARCH_TXS_RESULTS_GOTO_PAGE";
export const TOTAL_TXS_GET_COUNT = "TOTAL_TXS_GET_COUNT";
