export const ADD_API_CALL = "ADD_API_CALL";
export const REMOVE_API_CALL = "REMOVE_API_CALL";

export const SEARCH_TXS_RESULTS_LOADING = "SEARCH_TXS_RESULTS_LOADING";
export const SEARCH_TXS_RESULTS = "SEARCH_TXS_RESULTS";
export const SEARCH_TXS_RESULTS_PAGINATION_CHANGE = "SEARCH_TXS_RESULTS_PAGINATION_CHANGE";
export const SEARCH_TXS_RESULTS_FILTER_UPDATE = "SEARCH_TXS_RESULTS_FILTER_UPDATE";
export const TOTAL_TXS_COUNT_RESULTS = "TOTAL_TXS_COUNT_RESULTS";

export const TRENDING_COINS_RESULTS_LOADING = "TRENDING_COINS_RESULTS_LOADING";
export const TRENDING_COINS_RESULTS = "TRENDING_COINS_RESULTS";
